image: golang:1.8.3-alpine

stages:
  - build
  - test

before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - cd /go/src/github.com/user/repo

build-my-project:
  stage: build
  script:
    - dep init
    - go build docklog.go

test-my-project:
  stage: test
  script:
    - dep update
    - go test -v -race -cover ./...